spring:
  # mysql 데이터베이스 설정
  datasource:
    url: jdbc:mysql://localhost:3306/chatapp_test
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true

  # 프로파일 설정
  profiles:
    active: dev

  # RabbitMQ 설정
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    # 발행자 확인
    publisher-returns: true
    publisher-confirm-type: correlated
  web:
    cors:
        allowed-origins: http://localhost:3000
        allowed-methods: GET, POST, PUT, DELETE, OPTIONS
        allowed-headers: Content-Type, Authorization
        allow-credentials: true
        max-age: 3600

# 로깅 설정
logging:
  level:
    org:
      hibernate: INFO
      hibernate.SQL: DEBUG
      hibernate.orm.jdbc.bind: TRACE
      hibernate.type: OFF
      hibernate.engine.jdbc: OFF
    com:
      example:
        chatapp:
          repository: DEBUG
    com.example.chatapp.infrastructure.filter: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    com.example.chatapp: DEBUG



# 서버 포트 설정
server:
  port: 8080

# 애플리케이션 커스텀 설정
chat:
  websocket:
    endpoint: /ws
    allowed-origins:
      - http://localhost:3000
      - http://localhost:8080

