# src/main/resources/application.yml
spring:
  #  # 데이터소스 설정
  #  datasource:
  #    url: jdbc:h2:mem:chatdb
  #    driverClassName: org.h2.Driver
  #    username: sa
  #    password:

  # mysql 데이터베이스 설정
  datasource:
    url: jdbc:mysql://localhost:3306/my_database
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  # H2 데이터베이스 콘솔 설정
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false  # 중복 로깅 방지를 위해 false로 설정
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        # 쿼리 파라미터 값 로깅
        type: trace

  # 프로파일 설정
  profiles:
    active: dev

  # RabbitMQ 설정
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    # 발행자 확인
    publisher-returns: true
    publisher-confirm-type: correlated

# 로깅 설정
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
    com:
      example:
        chatapp:
          repository: debug  # 리포지토리 로깅 활성화

# 서버 포트 설정
server:
  port: 8080

# 애플리케이션 커스텀 설정
chat:
  websocket:
    endpoint: /ws
    allowed-origins:
      - http://localhost:3000
      - http://localhost:8080

jwt:
  secret: vAg3uL8nH6rP2tS5qY7xZ0dC1bF4mJ9oW2eR6vT8yU0iO3pA5sD7fG9hK1lZ3mN5bV6cX8dE0fG2hI4jK6lM8nO0pQ2rS4tU6vW8
  token-validity-in-seconds: 86400  # 토큰 유효 기간: 24시간
