# 공통 설정 (모든 환경에서 사용)
spring:
  application:
    name: chat-app

  # 프로파일 설정
  profiles:
    active: dev

  # JPA 공통 설정
  jpa:
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: false

# 서버 기본 설정
server:
  port: 8080

# 애플리케이션 커스텀 설정
chat:
  websocket:
    endpoint: /ws

# JWT 설정
app:
  jwt:
    secret: ${JWT_SECRET}  # 필수 환경변수 (기본값 없음)
    expiration: ${JWT_EXPIRATION:1800000}  # 30분 (밀리초)
